# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-craft"
client_id = "773cde6d5df26cbc4420efe7263667c4"
application_url = "https://cisco-victory-copy-sig.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cisco-victory-copy-sig.trycloudflare.com/auth/callback",
  "https://cisco-victory-copy-sig.trycloudflare.com/auth/shopify/callback",
  "https://cisco-victory-copy-sig.trycloudflare.com/api/auth/callback",
  "https://cisco-victory-copy-sig.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abel-developer.myshopify.com"
